[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jorm"
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
exclude = ["tests"]