from typing import Final

SAMPLES_COUNT: Final[int] = 20
DAYS_IN_MONTH: Final[int] = 30

DEFAULT_CATEGORY_NAME: Final[str] = "DEFAULT_CATEGORY"
DEFAULT_NICHE_NAME: Final[str] = "DEFAULT_NICHE"
DEFAULT_WAREHOUSE_NAME: Final[str] = "DEFAULT_WAREHOUSE"
DEFAULT_MARKETPLACE_NAME: Final[str] = "DEFAULT_MARKETPLACE"
