SAMPLES_COUNT: int = 20
DAYS_IN_MONTH: int = 30

DEFAULT_CATEGORY_NAME = "DEFAULT_CATEGORY"
DEFAULT_NICHE_NAME = "DEFAULT_NICHE"
DEFAULT_WAREHOUSE_NAME = "DEFAULT_WAREHOUSE"
DEFAULT_MARKETPLACE_NAME = "DEFAULT MARKETPLACE"
